books = [
  {
    ISBN: 1,
    Name: "Book1",
    Category: "Science",
    NumberOP: 30,
    Author: "NickCage1",
    Price: 10,
    Image: "https://www.placecage.com/gif/200/300",
  },
  {
    ISBN: 2,
    Name: "Book2",
    Category: "Action",
    NumberOP: 50,
    Author: "NickCage2",
    Price: 50,
    Image: "https://www.placecage.com/gif/250/300",
  },
  {
    ISBN: 3,
    Name: "Book3",
    Category: "Science",
    NumberOP: 100,
    Author: "NickCage3",
    Price: 120,
    Image: "https://www.placecage.com/gif/300/300",
  },
  {
    ISBN: 4,
    Name: "Book4",
    Category: "Action",
    NumberOP: 25,
    Author: "NickCage4",
    Price: 20,
    Image: "https://www.placecage.com/gif/250/300",
  },
  {
    ISBN: 5,
    Name: "Book5",
    Category: "Science",
    NumberOP: 40,
    Author: "NickCage5",
    Price: 40,
    Image: "https://www.placecage.com/gif/100/300",
  },
  {
    ISBN: 6,
    Name: "Book6",
    Category: "Action",
    NumberOP: 55,
    Author: "NickCage6",
    Price: 30,
    Image: "https://www.placecage.com/gif/100/100",
  },
  {
    ISBN: 7,
    Name: "Book7",
    Category: "Science",
    NumberOP: 150,
    Author: "NickCage7",
    Price: 10,
    Image: "https://www.placecage.com/gif/100/200",
  },
  {
    ISBN: 8,
    Name: "Book8",
    Category: "Action",
    NumberOP: 200,
    Author: "NickCage8",
    Price: 150,
    Image: "https://www.placecage.com/gif/201/340",
  },
  {
    ISBN: 9,
    Name: "Book9",
    Category: "Action",
    NumberOP: 100,
    Author: "NickCage9",
    Price: 120,
    Image: "https://www.placecage.com/gif/222/323",
  },
  {
    ISBN: 11,
    Name: "Book10",
    Category: "Action",
    NumberOP: 30,
    Author: "NickCage10",
    Price: 20,
    Image: "https://www.placecage.com/gif/220/315",
  },
  {
    ISBN: 11,
    Name: "Book11",
    Category: "Action",
    NumberOP: 30,
    Author: "NickCage11",
    Price: 20,
    Image: "https://www.placecage.com/gif/220/315",
  },
  {
    ISBN: 12,
    Name: "Book12",
    Category: "Action",
    NumberOP: 30,
    Author: "NickCage12",
    Price: 20,
    Image: "https://www.placecage.com/gif/220/315",
  },
];
